import { Provider } from '@/types/provider';

export const sampleProviders: Provider[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    title: 'MD',
    specialties: ['Family Medicine', 'Internal Medicine'],
    insuranceAccepted: ['Medicare', 'Medicaid', 'Blue Cross Blue Shield', 'Private Pay/Self-Pay'],
    servicesProvided: ['Primary Care', 'Preventive Care', 'Chronic Disease Management', 'Annual Physicals'],
    organization: 'Robeson Health Care Corporation',
    address: '123 Main St, Lumberton, NC 28358',
    phone: '(910) 555-0001',
    email: 'sjohnson@rhcc.org',
    website: 'https://www.robesonhealthcare.org',
    acceptingNewPatients: true,
    languages: ['English', 'Spanish'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    bio: 'Dr. Johnson has been serving the Robeson County community for over 15 years.',
    telehealth: true,
    slidingScale: true,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6180,
    longitude: -79.0124
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    title: 'MD',
    specialties: ['Pediatrics'],
    insuranceAccepted: ['Medicaid', 'NC Health Choice', 'UnitedHealthcare', 'Aetna'],
    servicesProvided: ['Pediatric Care', 'Immunizations', 'Well-Child Visits', 'Sick Visits'],
    organization: 'Lumberton Children\'s Clinic',
    address: '456 Oak Ave, Lumberton, NC 28358',
    phone: '(910) 555-0002',
    email: 'mchen@lumbertonpeds.com',
    acceptingNewPatients: true,
    languages: ['English', 'Mandarin'],
    hours: 'Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 12:00 PM',
    telehealth: false,
    slidingScale: false,
    medicareProvider: false,
    medicaidProvider: true,
    latitude: 34.6220,
    longitude: -79.0080
  },
  {
    id: '3',
    name: 'Maria Rodriguez',
    title: 'LCSW',
    specialties: ['Mental Health', 'Social Work'],
    insuranceAccepted: ['Medicaid', 'Blue Cross Blue Shield', 'Private Pay/Self-Pay', 'Sliding Scale Available'],
    servicesProvided: ['Individual Therapy', 'Family Counseling', 'Trauma Therapy', 'Crisis Intervention'],
    organization: 'Southeastern Regional Mental Health',
    address: '789 Pine St, Pembroke, NC 28372',
    phone: '(910) 555-0003',
    email: 'mrodriguez@srmh.org',
    acceptingNewPatients: true,
    languages: ['English', 'Spanish'],
    hours: 'Mon-Thu: 9:00 AM - 7:00 PM, Fri: 9:00 AM - 5:00 PM',
    telehealth: true,
    slidingScale: true,
    medicareProvider: false,
    medicaidProvider: true,
    latitude: 34.6802,
    longitude: -79.1950
  },
  {
    id: '4',
    name: 'Dr. James Thompson',
    title: 'PhD',
    specialties: ['Psychology', 'Behavioral Health'],
    insuranceAccepted: ['Medicare', 'Medicaid', 'TRICARE', 'Cigna'],
    servicesProvided: ['Psychological Testing', 'Cognitive Behavioral Therapy', 'ADHD Assessment', 'Depression Treatment'],
    organization: 'Robeson County Behavioral Health',
    address: '321 Elm St, Lumberton, NC 28358',
    phone: '(910) 555-0004',
    email: 'jthompson@rcbh.org',
    acceptingNewPatients: false,
    languages: ['English'],
    hours: 'Mon-Fri: 8:30 AM - 5:00 PM',
    telehealth: true,
    slidingScale: false,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6150,
    longitude: -79.0150
  },
  {
    id: '5',
    name: 'Dr. Ashley Williams',
    title: 'MD',
    specialties: ['OB/GYN'],
    insuranceAccepted: ['Medicaid', 'Blue Cross Blue Shield', 'Aetna', 'Humana'],
    servicesProvided: ['Prenatal Care', 'Women\'s Health', 'Family Planning', 'Gynecological Care'],
    organization: 'Southeastern Women\'s Healthcare',
    address: '555 Maple Dr, Lumberton, NC 28358',
    phone: '(910) 555-0005',
    email: 'awilliams@swh.org',
    website: 'https://www.swhealthcare.org',
    acceptingNewPatients: true,
    languages: ['English'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    telehealth: false,
    slidingScale: true,
    medicareProvider: false,
    medicaidProvider: true,
    latitude: 34.6200,
    longitude: -79.0200
  },
  {
    id: '6',
    name: 'Robert Locklear',
    title: 'NP',
    specialties: ['Family Medicine', 'Substance Abuse Counseling'],
    insuranceAccepted: ['Medicaid', 'Medicare', 'Private Pay/Self-Pay', 'Free/Pro Bono'],
    servicesProvided: ['Primary Care', 'Substance Abuse Treatment', 'MAT Services', 'Health Education'],
    organization: 'Lumbee Tribe Health Services',
    address: '900 Union Chapel Rd, Pembroke, NC 28372',
    phone: '(910) 555-0006',
    email: 'rlocklear@lumbeetribe.com',
    acceptingNewPatients: true,
    languages: ['English', 'Lumbee'],
    hours: 'Mon-Fri: 7:30 AM - 4:30 PM',
    bio: 'Specializing in culturally sensitive care for the Native American community.',
    telehealth: true,
    slidingScale: true,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6850,
    longitude: -79.2000
  },
  {
    id: '7',
    name: 'Dr. Patricia Davis',
    title: 'MD',
    specialties: ['Psychiatry', 'Mental Health'],
    insuranceAccepted: ['Medicare', 'Medicaid', 'Blue Cross Blue Shield', 'UnitedHealthcare'],
    servicesProvided: ['Psychiatric Evaluation', 'Medication Management', 'Mental Health Treatment', 'Crisis Stabilization'],
    organization: 'Southeastern Psychiatric Associates',
    address: '1200 Roberts Ave, Lumberton, NC 28358',
    phone: '(910) 555-0007',
    email: 'pdavis@sepych.com',
    acceptingNewPatients: true,
    languages: ['English', 'French'],
    hours: 'Mon-Thu: 8:00 AM - 6:00 PM',
    telehealth: true,
    slidingScale: false,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6100,
    longitude: -79.0050
  },
  {
    id: '8',
    name: 'Jennifer Brooks',
    title: 'PA-C',
    specialties: ['Emergency Medicine', 'Family Medicine'],
    insuranceAccepted: ['All Insurance Types Accepted', 'Medicaid', 'Medicare', 'Private Pay/Self-Pay'],
    servicesProvided: ['Urgent Care', 'Minor Injuries', 'Illness Treatment', 'Physical Exams'],
    organization: 'FirstHealth Convenient Care',
    address: '2400 N Elm St, Lumberton, NC 28358',
    phone: '(910) 555-0008',
    email: 'jbrooks@firsthealth.org',
    acceptingNewPatients: true,
    languages: ['English', 'Spanish'],
    hours: 'Mon-Sun: 8:00 AM - 8:00 PM',
    telehealth: false,
    slidingScale: false,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6300,
    longitude: -79.0300
  },
  {
    id: '9',
    name: 'Dr. Kevin Martinez',
    title: 'DDS',
    specialties: ['Dentistry'],
    insuranceAccepted: ['Medicaid', 'NC Health Choice', 'Private Pay/Self-Pay', 'Sliding Scale Available'],
    servicesProvided: ['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'],
    organization: 'Robeson County Dental Clinic',
    address: '850 Caton Rd, Lumberton, NC 28358',
    phone: '(910) 555-0009',
    email: 'kmartinez@rcdentalclinic.org',
    acceptingNewPatients: true,
    languages: ['English', 'Spanish'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    telehealth: false,
    slidingScale: true,
    medicareProvider: false,
    medicaidProvider: true,
    latitude: 34.6250,
    longitude: -79.0250
  },
  {
    id: '10',
    name: 'Lisa Chang',
    title: 'PT',
    specialties: ['Physical Therapy'],
    insuranceAccepted: ['Medicare', 'Medicaid', 'Blue Cross Blue Shield', 'Aetna', 'Workers Compensation'],
    servicesProvided: ['Physical Rehabilitation', 'Sports Injury Treatment', 'Post-Surgery Recovery', 'Pain Management'],
    organization: 'Southeastern Physical Therapy',
    address: '1800 Godwin Ave, Lumberton, NC 28358',
    phone: '(910) 555-0010',
    email: 'lchang@southeasternpt.com',
    acceptingNewPatients: true,
    languages: ['English', 'Korean'],
    hours: 'Mon-Fri: 7:00 AM - 6:00 PM',
    telehealth: false,
    slidingScale: false,
    medicareProvider: true,
    medicaidProvider: true,
    latitude: 34.6180,
    longitude: -79.0180
  }
];